sudo: required 
services:
  - docker

before_install:
  - docker build -t devopsimage -f Dockerfile.dev .

script:
  - docker run -e CI=true devopsimage npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "docker"
  env: "Docker-env"
  bucket_name: "name of the s3 bucket"
  bucket_path: "docker"
  on:
    branch: master